name: SurfaceSnap

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Target domain (e.g., example.com)'
        required: true
        type: string

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Set up environment
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y curl unzip libpcap-dev

          mkdir -p "$HOME/tools"
          echo "$HOME/tools" >> $GITHUB_PATH

      - name: Download ProjectDiscovery Tools
        run: |
          set -e
          # Subfinder
          echo "Attempting to download subfinder..."
          curl -L -o subfinder.zip https://github.com/projectdiscovery/subfinder/releases/download/v2.7.7/subfinder_2.7.7_linux_amd64.zip
          CURL_EXIT_CODE=$?
          if [ $CURL_EXIT_CODE -ne 0 ]; then
              echo "Error: curl failed to download subfinder.zip. Exit code: $CURL_EXIT_CODE"
              exit $CURL_EXIT_CODE
          fi
          echo "Files in current directory after subfinder download:"
          ls -la
          unzip -j subfinder.zip subfinder -d "$HOME/tools"
          rm subfinder.zip

          # Httpx
          echo "Attempting to download httpx..."
          curl -L -o httpx.zip https://github.com/projectdiscovery/httpx/releases/download/v1.6.5/httpx_1.6.5_linux_amd64.zip
          CURL_EXIT_CODE=$?
          if [ $CURL_EXIT_CODE -ne 0 ]; then
              echo "Error: curl failed to download httpx.zip. Exit code: $CURL_EXIT_CODE"
              exit $CURL_EXIT_CODE
          fi
          echo "Files in current directory after httpx download:"
          ls -la
          unzip -j httpx.zip httpx -d "$HOME/tools"
          rm httpx.zip

          # Naabu
          echo "Attempting to download naabu..."
          curl -L -o naabu.zip https://github.com/projectdiscovery/naabu/releases/download/v2.3.2/naabu_2.3.2_linux_amd64.zip
          CURL_EXIT_CODE=$?
          if [ $CURL_EXIT_CODE -ne 0 ]; then
              echo "Error: curl failed to download naabu.zip. Exit code: $CURL_EXIT_CODE"
              exit $CURL_EXIT_CODE
          fi
          echo "Files in current directory after naabu download:"
          ls -la
          unzip -j naabu.zip naabu -d "$HOME/tools"
          rm naabu.zip

          # Nuclei
          echo "Attempting to download nuclei..."
          curl -L -o nuclei.zip https://github.com/projectdiscovery/nuclei/releases/download/v3.2.5/nuclei_3.2.5_linux_amd64.zip
          CURL_EXIT_CODE=$?
          if [ $CURL_EXIT_CODE -ne 0 ]; then
              echo "Error: curl failed to download nuclei.zip. Exit code: $CURL_EXIT_CODE"
              exit $CURL_EXIT_CODE
          fi
          echo "Files in current directory after nuclei download:"
          ls -la
          unzip -j nuclei.zip nuclei -d "$HOME/tools"
          rm nuclei.zip

          chmod +x "$HOME/tools"/*

      - name: Update Nuclei Templates (optional but recommended)
        run: |
          set -e
          nuclei -update-templates

      - name: Run Scan Pipeline
        run: |
          set -e
          DOMAIN="${{ github.event.inputs.domain }}"

          echo "Running subfinder..."
          subfinder -d "$DOMAIN" -silent -o subdomains.txt

          echo "Running httpx..."
          httpx -l subdomains.txt -silent -o live.txt

          echo "Running naabu..."
          naabu -l live.txt -top-ports 100 -silent -o ports.txt

          echo "Running nuclei..."
          nuclei -l live.txt -silent -json -o findings.json

      - name: Upload Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: SurfaceSnap-Report
          path: findings.json
