name: SurfaceSnap Scanner

on:
  workflow_dispatch:
    inputs:
      domain:
        description: "Domain to scan (e.g. example.com)"
        required: true

env:
  TOOLS_DIR: ${{ github.workspace }}/tools          # one temp dir for all binaries
  SUBF_VER: v2.7.7                                  # pin to stable versions
  HTTPX_VER: v1.6.5
  NUCLEI_VER: v3.2.5
  NAABU_VER: v2.3.2

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    # ------------------------------------------------
    # 1) Minimal OS packages we need
    # ------------------------------------------------
    - name: Install system deps
      run: |
        sudo apt-get update -y
        sudo apt-get install -y unzip zip curl libpcap-dev

    # ------------------------------------------------
    # 2) Make tools folder & add to PATH
    # ------------------------------------------------
    - name: Prepare tools dir
      run: |
        mkdir -p "${TOOLS_DIR}"
        echo "${TOOLS_DIR}" >> $GITHUB_PATH

    # ------------------------------------------------
    # 3) Download pre-built binaries (zip archives)
    # ------------------------------------------------
    - name: Download ProjectDiscovery binaries
      working-directory: ${{ env.TOOLS_DIR }}
      run: |
        # --- subfinder ---
        curl -L -o sub.zip \
          "https://github.com/projectdiscovery/subfinder/releases/download/${{ env.SUBF_VER }}/subfinder_${{ env.SUBF_VER }}_linux_amd64.zip"
        unzip -j sub.zip -d . subfinder
        rm sub.zip

        # --- httpx ---
        curl -L -o httpx.zip \
          "https://github.com/projectdiscovery/httpx/releases/download/${{ env.HTTPX_VER }}/httpx_${{ env.HTTPX_VER }}_linux_amd64.zip"
        unzip -j httpx.zip -d . httpx
        rm httpx.zip

        # --- nuclei ---
        curl -L -o nu
