# .github/workflows/surfacesnap.yml
name: SurfaceSnap Scanner

on:
  workflow_dispatch:
    inputs:
      domain:
        description: "Domain to scan (e.g. example.com)"
        required: true

env:
  TOOLS_DIR: ${{ github.workspace }}/tools       # directory to hold binaries
  SUBF_VER: v2.7.7                               # pin stable versions
  HTTPX_VER: v1.6.5
  NUCLEI_VER: v3.2.5
  NAABU_VER: v2.3.2

jobs:
  scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    # --------------------------------------------------------------
    # 1) System dependencies required by naabu (libpcap) and unzip
    # --------------------------------------------------------------
    - name: Install OS packages
      run: |
        sudo apt-get update -y
        sudo apt-get install -y curl unzip libpcap-dev

    # --------------------------------------------------------------
    # 2) Prepare tools directory and add to PATH
    # --------------------------------------------------------------
    - name: Prepare tools directory
      run: |
        mkdir -p "$TOOLS_DIR"
        echo "$TOOLS_DIR" >> $GITHUB_PATH

    # --------------------------------------------------------------
    # 3) Download pre-built binaries (no compiling, no Go needed)
    # --------------------------------------------------------------
    - name: Fetch ProjectDiscovery binaries
      working-directory: ${{ env.TOOLS_DIR }}
      run: |
        set -e
        download() {
          local url="$1" file="$2"
          echo "Downloading $file …"
          curl -sSL "$url" -o "$file" && unzip -jo "$file" && rm "$file"
        }

        download "https://github.com/projectdiscovery/subfinder/releases/download/${SUBF_VER}/subfinder_${SUBF_VER#v}_linux_amd64.zip" subfinder.zip
        download "https://github.com/projectdiscovery/httpx/releases/download/${HTTPX_VER}/httpx_${HTTPX_VER#v}_linux_amd64.zip" httpx.zip
        download "https://github.com/projectdiscovery/nuclei/releases/download/${NUCLEI_VER}/nuclei_${NUCLEI_VER#v}_linux_amd64.zip" nuclei.zip
        download "https://github.com/projectdiscovery/naabu/releases/download/${NAABU_VER}/naabu_${NAABU_VER#v}_linux_amd64.zip" naabu.zip

        # Update nuclei templates (latest vulnerability signatures)
        nuclei -update-templates

    # --------------------------------------------------------------
    # 4) Run the SurfaceSnap scan pipeline
    # --------------------------------------------------------------
    - name: Execute scan pipeline
      run: |
        set -e
        DOMAIN="${{ github.event.inputs.domain }}"

        echo "[+] Subdomain discovery…"
        subfinder -d "$DOMAIN" -silent -o subdomains.txt

        echo "[+] Alive check…"
        httpx -l subdomains.txt -silent -o live.txt

        echo "[+] Port scan (top‑100)…"
        naabu -l live.txt -top-ports 100 -silent -o ports.txt

        echo "[+] Vulnerability scan…"
        nuclei -l live.txt -json -silent -o findings.json

    # --------------------------------------------------------------
    # 5) Upload findings as workflow artifact
    # --------------------------------------------------------------
    - name: Upload findings.json
      uses: actions/upload-artifact@v4
      with:
        name: SurfaceSnap-Report
        path: findings.json
