name: SurfaceSnap Scanner
on:
  workflow_dispatch:  # For manual testing
    inputs:
      domain:
        description: 'Target domain'
        required: true
        default: 'example.com'
  repository_dispatch: # For API triggering
    types: [run_scan]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Install OS Dependencies
      run: sudo apt-get update && sudo apt-get install -y libpcap-dev

      
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        
    - name: Install Tools
      run: |
        go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
        go install github.com/projectdiscovery/naabu/v2/cmd/naabu@latest
        go install github.com/projectdiscovery/httpx/cmd/httpx@latest
        go install github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
        sudo mv ~/go/bin/* /usr/local/bin/
        
    - name: Run Security Scan
      run: |
        # Get domain from input
        DOMAIN="${{ github.event.inputs.domain || github.event.client_payload.domain }}"
        
        # Discovery
        subfinder -d $DOMAIN -o subs.txt
        naabu -list subs.txt -top-ports 1000 -o naabu.txt
        
        # HTTP Probe
        httpx -l naabu.txt -title -status-code -tech-detect -json -o httpx.json
        
        # Vulnerability Scan
        nuclei -u $DOMAIN -j -o nuclei.json -severity medium,critical
        
        # Combine results
        jq -s 'add' httpx.json nuclei.json > results.json
        
    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: scan-results
        path: |
          results.json
          subs.txt
          naabu.txt
